baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "CanoKey Documentation"
theme = "hugo-theme-learn"

[markup.goldmark.renderer]
  unsafe = true

[Languages]
[Languages.en]
title = "CanoKey"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[Languages.zh-hans]
title = "CanoKey"
weight = 2
languageName = "简体中文"
landingPageURL = "/zh-Hans"
landingPageName = "<i class='fas fa-home'></i> 首页"
